FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 8080

FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["Stockpile.Api/Stockpile.Api.csproj", "Stockpile.Api/"]
COPY ["Stockpile.DAL/Stockpile.DAL.csproj", "Stockpile.DAL/"]

RUN dotnet restore "Stockpile.Api/Stockpile.Api.csproj"
COPY . .
WORKDIR "/src/Stockpile.Api"
RUN dotnet build "Stockpile.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Stockpile.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Stockpile.Api.dll"]
