using Stockpile.Api.Contracts.Requests;
using Stockpile.Api.Contracts.Response;
using Stockpile.Domain.Entities;

namespace Stockpile.Api.Contracts.Mappers;

public static class InventoryItemMapper
{
    /// <summary>
    /// When updating an existing item, we need to provide the id, userId and username
    /// </summary>
    /// <param name="request"></param>
    /// <param name="id"></param>
    /// <param name="userId"></param>
    /// <param name="username"></param>
    /// <returns></returns>
    public static InventoryItem MapTo(this InventoryItemRequest request, string id, string userId, string username)
    {
        return new InventoryItem(id)
        {
            Name = request.Name,
            Quantity = request.Quantity,
            Unit = request.Unit,
            ExpiryDate = request.ExpiryDate,
            UserId = userId,
            Username = username
        };
    }

    /// <summary>
    /// Creating a new item, id will be generated by the InventoryItem constructor
    /// </summary>
    /// <param name="request"></param>
    /// <param name="userId"></param>
    /// <param name="username"></param>
    /// <returns></returns>
    public static InventoryItem MapTo(this InventoryItemRequest request, string userId, string username)
    {
        return new InventoryItem
        {
            Name = request.Name,
            Quantity = request.Quantity,
            Unit = request.Unit,
            ExpiryDate = request.ExpiryDate,
            UserId = userId,
            Username = username
        };
    }
    
    public static InventoryItemResponse MapFrom(this InventoryItem item)
    {
        return new InventoryItemResponse
        {
            Id = item.Id,
            Name = item.Name,
            Quantity = item.Quantity,
            Unit = item.Unit,
            ExpiryDate = item.ExpiryDate
        };
    }
}