//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.7.1.0 (NJsonSchema v11.6.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from 'axios';
import type { AxiosInstance, AxiosRequestConfig, AxiosResponse, CancelToken } from 'axios';

export interface IApiClient {
    /**
     * Query inventory with agent-friendly server-side filtering and sorting.
     * @param search (optional) Case-insensitive search across name, category, location, and notes.
     * @param category (optional) Case-insensitive exact category filter, for example "Dairy".
     * @param location (optional) Case-insensitive exact location filter, for example "Fridge".
     * @param expiresFrom (optional) Inclusive UTC expiry lower bound.
     * @param expiresTo (optional) Inclusive UTC expiry upper bound.
     * @param includeNoExpiry (optional) Include items that do not have an expiry date. Defaults to false to reduce agent context size.
     * @param sort (optional) Server-side sort field. Defaults to earliest expiry first.
     * @param descending (optional) Reverse the selected sort. Defaults to false.
     * @param limit (optional) Maximum number of items returned. Clamped to 1-200.
     * @return OK
     */
    queryAgentInventory(search?: string | undefined, category?: string | undefined, location?: string | undefined, expiresFrom?: Date | undefined, expiresTo?: Date | undefined, includeNoExpiry?: boolean | undefined, sort?: InventoryAgentSort | undefined, descending?: boolean | undefined, limit?: number | undefined, signal?: AbortSignal): Promise<InventoryAgentQueryResponse>;
    /**
     * Get the compact cron digest the agent should use for routine inventory updates.
     * @param asOf (optional) UTC date used as "today" for expiry grouping. Defaults to the current UTC date.
     * @param limitPerSection (optional) Maximum number of items in each digest section. Clamped to 1-100.
     * @param includeNoExpiry (optional) Include a compact section for items without expiry dates.
     * @return OK
     */
    getAgentInventoryDigest(asOf?: Date | undefined, limitPerSection?: number | undefined, includeNoExpiry?: boolean | undefined, signal?: AbortSignal): Promise<InventoryDigestResponse>;
    /**
     * @param body (optional) 
     * @return OK
     */
    login(body?: LoginRequest | undefined, signal?: AbortSignal): Promise<string>;
    /**
     * @return OK
     */
    getStock(signal?: AbortSignal): Promise<InventoryItemResponse[]>;
    /**
     * @param body (optional) 
     * @return Created
     */
    addStock(body?: InventoryItemRequest | undefined, signal?: AbortSignal): Promise<InventoryItemResponse>;
    /**
     * @return OK
     */
    getStockById(id: string, signal?: AbortSignal): Promise<InventoryItemResponse>;
    /**
     * @param body (optional) 
     * @return OK
     */
    updateStock(id: string, body?: InventoryItemRequest | undefined, signal?: AbortSignal): Promise<InventoryItemResponse>;
    /**
     * @return No Content
     */
    deleteStock(id: string, signal?: AbortSignal): Promise<void>;
}

export class ApiClient implements IApiClient {
    protected instance: AxiosInstance;
    protected baseUrl: string;
    protected jsonParseReviver: ((key: string, value: any) => any) | undefined = undefined;

    constructor(baseUrl?: string, instance?: AxiosInstance) {

        this.instance = instance || axios.create();

        this.baseUrl = baseUrl ?? "";

    }

    /**
     * Query inventory with agent-friendly server-side filtering and sorting.
     * @param search (optional) Case-insensitive search across name, category, location, and notes.
     * @param category (optional) Case-insensitive exact category filter, for example "Dairy".
     * @param location (optional) Case-insensitive exact location filter, for example "Fridge".
     * @param expiresFrom (optional) Inclusive UTC expiry lower bound.
     * @param expiresTo (optional) Inclusive UTC expiry upper bound.
     * @param includeNoExpiry (optional) Include items that do not have an expiry date. Defaults to false to reduce agent context size.
     * @param sort (optional) Server-side sort field. Defaults to earliest expiry first.
     * @param descending (optional) Reverse the selected sort. Defaults to false.
     * @param limit (optional) Maximum number of items returned. Clamped to 1-200.
     * @return OK
     */
    queryAgentInventory(search?: string | undefined, category?: string | undefined, location?: string | undefined, expiresFrom?: Date | undefined, expiresTo?: Date | undefined, includeNoExpiry?: boolean | undefined, sort?: InventoryAgentSort | undefined, descending?: boolean | undefined, limit?: number | undefined, signal?: AbortSignal): Promise<InventoryAgentQueryResponse> {
        let url_ = this.baseUrl + "/api/agent/inventory/query?";
        if (search === null)
            throw new globalThis.Error("The parameter 'search' cannot be null.");
        else if (search !== undefined)
            url_ += "Search=" + encodeURIComponent("" + search) + "&";
        if (category === null)
            throw new globalThis.Error("The parameter 'category' cannot be null.");
        else if (category !== undefined)
            url_ += "Category=" + encodeURIComponent("" + category) + "&";
        if (location === null)
            throw new globalThis.Error("The parameter 'location' cannot be null.");
        else if (location !== undefined)
            url_ += "Location=" + encodeURIComponent("" + location) + "&";
        if (expiresFrom === null)
            throw new globalThis.Error("The parameter 'expiresFrom' cannot be null.");
        else if (expiresFrom !== undefined)
            url_ += "ExpiresFrom=" + encodeURIComponent(expiresFrom ? "" + expiresFrom.toISOString() : "") + "&";
        if (expiresTo === null)
            throw new globalThis.Error("The parameter 'expiresTo' cannot be null.");
        else if (expiresTo !== undefined)
            url_ += "ExpiresTo=" + encodeURIComponent(expiresTo ? "" + expiresTo.toISOString() : "") + "&";
        if (includeNoExpiry === null)
            throw new globalThis.Error("The parameter 'includeNoExpiry' cannot be null.");
        else if (includeNoExpiry !== undefined)
            url_ += "IncludeNoExpiry=" + encodeURIComponent("" + includeNoExpiry) + "&";
        if (sort === null)
            throw new globalThis.Error("The parameter 'sort' cannot be null.");
        else if (sort !== undefined)
            url_ += "Sort=" + encodeURIComponent("" + sort) + "&";
        if (descending === null)
            throw new globalThis.Error("The parameter 'descending' cannot be null.");
        else if (descending !== undefined)
            url_ += "Descending=" + encodeURIComponent("" + descending) + "&";
        if (limit === null)
            throw new globalThis.Error("The parameter 'limit' cannot be null.");
        else if (limit !== undefined)
            url_ += "Limit=" + encodeURIComponent("" + limit) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processQueryAgentInventory(_response);
        });
    }

    protected processQueryAgentInventory(response: AxiosResponse): Promise<InventoryAgentQueryResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = InventoryAgentQueryResponse.fromJS(resultData200);
            return Promise.resolve<InventoryAgentQueryResponse>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            let result401: any = null;
            let resultData401  = _responseText;
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);

        } else if (status === 403) {
            const _responseText = response.data;
            let result403: any = null;
            let resultData403  = _responseText;
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<InventoryAgentQueryResponse>(null as any);
    }

    /**
     * Get the compact cron digest the agent should use for routine inventory updates.
     * @param asOf (optional) UTC date used as "today" for expiry grouping. Defaults to the current UTC date.
     * @param limitPerSection (optional) Maximum number of items in each digest section. Clamped to 1-100.
     * @param includeNoExpiry (optional) Include a compact section for items without expiry dates.
     * @return OK
     */
    getAgentInventoryDigest(asOf?: Date | undefined, limitPerSection?: number | undefined, includeNoExpiry?: boolean | undefined, signal?: AbortSignal): Promise<InventoryDigestResponse> {
        let url_ = this.baseUrl + "/api/agent/inventory/digest?";
        if (asOf === null)
            throw new globalThis.Error("The parameter 'asOf' cannot be null.");
        else if (asOf !== undefined)
            url_ += "AsOf=" + encodeURIComponent(asOf ? "" + asOf.toISOString() : "") + "&";
        if (limitPerSection === null)
            throw new globalThis.Error("The parameter 'limitPerSection' cannot be null.");
        else if (limitPerSection !== undefined)
            url_ += "LimitPerSection=" + encodeURIComponent("" + limitPerSection) + "&";
        if (includeNoExpiry === null)
            throw new globalThis.Error("The parameter 'includeNoExpiry' cannot be null.");
        else if (includeNoExpiry !== undefined)
            url_ += "IncludeNoExpiry=" + encodeURIComponent("" + includeNoExpiry) + "&";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetAgentInventoryDigest(_response);
        });
    }

    protected processGetAgentInventoryDigest(response: AxiosResponse): Promise<InventoryDigestResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = InventoryDigestResponse.fromJS(resultData200);
            return Promise.resolve<InventoryDigestResponse>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            let result401: any = null;
            let resultData401  = _responseText;
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);

        } else if (status === 403) {
            const _responseText = response.data;
            let result403: any = null;
            let resultData403  = _responseText;
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<InventoryDigestResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    login(body?: LoginRequest | undefined, signal?: AbortSignal): Promise<string> {
        let url_ = this.baseUrl + "/api/Auth/login";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processLogin(_response);
        });
    }

    protected processLogin(response: AxiosResponse): Promise<string> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
                result200 = resultData200 !== undefined ? resultData200 : null as any;
    
            return Promise.resolve<string>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 401) {
            const _responseText = response.data;
            let result401: any = null;
            let resultData401  = _responseText;
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<string>(null as any);
    }

    /**
     * @return OK
     */
    getStock(signal?: AbortSignal): Promise<InventoryItemResponse[]> {
        let url_ = this.baseUrl + "/api/Stock";
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetStock(_response);
        });
    }

    protected processGetStock(response: AxiosResponse): Promise<InventoryItemResponse[]> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            if (Array.isArray(resultData200)) {
                result200 = [] as any;
                for (let item of resultData200)
                    result200!.push(InventoryItemResponse.fromJS(item));
            }
            else {
                result200 = null as any;
            }
            return Promise.resolve<InventoryItemResponse[]>(result200);

        } else if (status === 401) {
            const _responseText = response.data;
            let result401: any = null;
            let resultData401  = _responseText;
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<InventoryItemResponse[]>(null as any);
    }

    /**
     * @param body (optional) 
     * @return Created
     */
    addStock(body?: InventoryItemRequest | undefined, signal?: AbortSignal): Promise<InventoryItemResponse> {
        let url_ = this.baseUrl + "/api/Stock";
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "POST",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processAddStock(_response);
        });
    }

    protected processAddStock(response: AxiosResponse): Promise<InventoryItemResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 201) {
            const _responseText = response.data;
            let result201: any = null;
            let resultData201  = _responseText;
            result201 = InventoryItemResponse.fromJS(resultData201);
            return Promise.resolve<InventoryItemResponse>(result201);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 401) {
            const _responseText = response.data;
            let result401: any = null;
            let resultData401  = _responseText;
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<InventoryItemResponse>(null as any);
    }

    /**
     * @return OK
     */
    getStockById(id: string, signal?: AbortSignal): Promise<InventoryItemResponse> {
        let url_ = this.baseUrl + "/api/Stock/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "GET",
            url: url_,
            headers: {
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processGetStockById(_response);
        });
    }

    protected processGetStockById(response: AxiosResponse): Promise<InventoryItemResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = InventoryItemResponse.fromJS(resultData200);
            return Promise.resolve<InventoryItemResponse>(result200);

        } else if (status === 403) {
            const _responseText = response.data;
            let result403: any = null;
            let resultData403  = _responseText;
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<InventoryItemResponse>(null as any);
    }

    /**
     * @param body (optional) 
     * @return OK
     */
    updateStock(id: string, body?: InventoryItemRequest | undefined, signal?: AbortSignal): Promise<InventoryItemResponse> {
        let url_ = this.baseUrl + "/api/Stock/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        const content_ = JSON.stringify(body);

        let options_: AxiosRequestConfig = {
            data: content_,
            method: "PUT",
            url: url_,
            headers: {
                "Content-Type": "application/json",
                "Accept": "application/json"
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processUpdateStock(_response);
        });
    }

    protected processUpdateStock(response: AxiosResponse): Promise<InventoryItemResponse> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 200) {
            const _responseText = response.data;
            let result200: any = null;
            let resultData200  = _responseText;
            result200 = InventoryItemResponse.fromJS(resultData200);
            return Promise.resolve<InventoryItemResponse>(result200);

        } else if (status === 400) {
            const _responseText = response.data;
            let result400: any = null;
            let resultData400  = _responseText;
            result400 = ProblemDetails.fromJS(resultData400);
            return throwException("Bad Request", status, _responseText, _headers, result400);

        } else if (status === 401) {
            const _responseText = response.data;
            let result401: any = null;
            let resultData401  = _responseText;
            result401 = ProblemDetails.fromJS(resultData401);
            return throwException("Unauthorized", status, _responseText, _headers, result401);

        } else if (status === 403) {
            const _responseText = response.data;
            let result403: any = null;
            let resultData403  = _responseText;
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<InventoryItemResponse>(null as any);
    }

    /**
     * @return No Content
     */
    deleteStock(id: string, signal?: AbortSignal): Promise<void> {
        let url_ = this.baseUrl + "/api/Stock/{id}";
        if (id === undefined || id === null)
            throw new globalThis.Error("The parameter 'id' must be defined.");
        url_ = url_.replace("{id}", encodeURIComponent("" + id));
        url_ = url_.replace(/[?&]$/, "");

        let options_: AxiosRequestConfig = {
            method: "DELETE",
            url: url_,
            headers: {
            },
            signal
        };

        return this.instance.request(options_).catch((_error: any) => {
            if (isAxiosError(_error) && _error.response) {
                return _error.response;
            } else {
                throw _error;
            }
        }).then((_response: AxiosResponse) => {
            return this.processDeleteStock(_response);
        });
    }

    protected processDeleteStock(response: AxiosResponse): Promise<void> {
        const status = response.status;
        let _headers: any = {};
        if (response.headers && typeof response.headers === "object") {
            for (const k in response.headers) {
                if (response.headers.hasOwnProperty(k)) {
                    _headers[k] = response.headers[k];
                }
            }
        }
        if (status === 204) {
            const _responseText = response.data;
            return Promise.resolve<void>(null as any);

        } else if (status === 403) {
            const _responseText = response.data;
            let result403: any = null;
            let resultData403  = _responseText;
            result403 = ProblemDetails.fromJS(resultData403);
            return throwException("Forbidden", status, _responseText, _headers, result403);

        } else if (status === 404) {
            const _responseText = response.data;
            let result404: any = null;
            let resultData404  = _responseText;
            result404 = ProblemDetails.fromJS(resultData404);
            return throwException("Not Found", status, _responseText, _headers, result404);

        } else if (status !== 200 && status !== 204) {
            const _responseText = response.data;
            return throwException("An unexpected server error occurred.", status, _responseText, _headers);
        }
        return Promise.resolve<void>(null as any);
    }
}

export class InventoryAgentHintResponse implements IInventoryAgentHintResponse {
    type!: string | undefined;
    priority!: string | undefined;
    message!: string | undefined;
    itemIds?: string[] | undefined;

    constructor(data?: IInventoryAgentHintResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.type = _data["type"];
            this.priority = _data["priority"];
            this.message = _data["message"];
            if (Array.isArray(_data["itemIds"])) {
                this.itemIds = [] as any;
                for (let item of _data["itemIds"])
                    this.itemIds!.push(item);
            }
        }
    }

    static fromJS(data: any): InventoryAgentHintResponse {
        data = typeof data === 'object' ? data : {};
        let result = new InventoryAgentHintResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["type"] = this.type;
        data["priority"] = this.priority;
        data["message"] = this.message;
        if (Array.isArray(this.itemIds)) {
            data["itemIds"] = [];
            for (let item of this.itemIds)
                data["itemIds"].push(item);
        }
        return data;
    }
}

export interface IInventoryAgentHintResponse {
    type: string | undefined;
    priority: string | undefined;
    message: string | undefined;
    itemIds?: string[] | undefined;
}

/** Compact inventory item optimized for agent context. */
export class InventoryAgentItemResponse implements IInventoryAgentItemResponse {
    id!: string | undefined;
    name!: string | undefined;
    quantity?: number;
    unit?: Unit;
    expiryDate?: Date | undefined;
    daysUntilExpiry?: number | undefined;
    urgency?: InventoryItemUrgency;
    category?: string | undefined;
    location?: string | undefined;
    purchasedDate?: Date | undefined;
    openedDate?: Date | undefined;
    notes?: string | undefined;

    constructor(data?: IInventoryAgentItemResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.quantity = _data["quantity"];
            this.unit = _data["unit"];
            this.expiryDate = _data["expiryDate"] ? new Date(_data["expiryDate"].toString()) : undefined as any;
            this.daysUntilExpiry = _data["daysUntilExpiry"];
            this.urgency = _data["urgency"];
            this.category = _data["category"];
            this.location = _data["location"];
            this.purchasedDate = _data["purchasedDate"] ? new Date(_data["purchasedDate"].toString()) : undefined as any;
            this.openedDate = _data["openedDate"] ? new Date(_data["openedDate"].toString()) : undefined as any;
            this.notes = _data["notes"];
        }
    }

    static fromJS(data: any): InventoryAgentItemResponse {
        data = typeof data === 'object' ? data : {};
        let result = new InventoryAgentItemResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["quantity"] = this.quantity;
        data["unit"] = this.unit;
        data["expiryDate"] = this.expiryDate ? this.expiryDate.toISOString() : undefined as any;
        data["daysUntilExpiry"] = this.daysUntilExpiry;
        data["urgency"] = this.urgency;
        data["category"] = this.category;
        data["location"] = this.location;
        data["purchasedDate"] = this.purchasedDate ? this.purchasedDate.toISOString() : undefined as any;
        data["openedDate"] = this.openedDate ? this.openedDate.toISOString() : undefined as any;
        data["notes"] = this.notes;
        return data;
    }
}

/** Compact inventory item optimized for agent context. */
export interface IInventoryAgentItemResponse {
    id: string | undefined;
    name: string | undefined;
    quantity?: number;
    unit?: Unit;
    expiryDate?: Date | undefined;
    daysUntilExpiry?: number | undefined;
    urgency?: InventoryItemUrgency;
    category?: string | undefined;
    location?: string | undefined;
    purchasedDate?: Date | undefined;
    openedDate?: Date | undefined;
    notes?: string | undefined;
}

/** Query result with server-side filters already applied. */
export class InventoryAgentQueryResponse implements IInventoryAgentQueryResponse {
    asOf?: Date;
    count?: number;
    items?: InventoryAgentItemResponse[] | undefined;

    constructor(data?: IInventoryAgentQueryResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.asOf = _data["asOf"] ? new Date(_data["asOf"].toString()) : undefined as any;
            this.count = _data["count"];
            if (Array.isArray(_data["items"])) {
                this.items = [] as any;
                for (let item of _data["items"])
                    this.items!.push(InventoryAgentItemResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): InventoryAgentQueryResponse {
        data = typeof data === 'object' ? data : {};
        let result = new InventoryAgentQueryResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["asOf"] = this.asOf ? this.asOf.toISOString() : undefined as any;
        data["count"] = this.count;
        if (Array.isArray(this.items)) {
            data["items"] = [];
            for (let item of this.items)
                data["items"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

/** Query result with server-side filters already applied. */
export interface IInventoryAgentQueryResponse {
    asOf?: Date;
    count?: number;
    items?: InventoryAgentItemResponse[] | undefined;
}

export enum InventoryAgentSort {
    ExpiryDate = "ExpiryDate",
    Name = "Name",
    Category = "Category",
    Location = "Location",
    CreatedAt = "CreatedAt",
}

export class InventoryDigestCountsResponse implements IInventoryDigestCountsResponse {
    expired?: number;
    dueWithinDays?: { [key: string]: number; } | undefined;
    noExpiry?: number;
    totalActionable?: number;

    constructor(data?: IInventoryDigestCountsResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.expired = _data["expired"];
            if (_data["dueWithinDays"]) {
                this.dueWithinDays = {} as any;
                for (let key in _data["dueWithinDays"]) {
                    if (_data["dueWithinDays"].hasOwnProperty(key))
                        (this.dueWithinDays as any)![key] = _data["dueWithinDays"][key];
                }
            }
            this.noExpiry = _data["noExpiry"];
            this.totalActionable = _data["totalActionable"];
        }
    }

    static fromJS(data: any): InventoryDigestCountsResponse {
        data = typeof data === 'object' ? data : {};
        let result = new InventoryDigestCountsResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["expired"] = this.expired;
        if (this.dueWithinDays) {
            data["dueWithinDays"] = {};
            for (let key in this.dueWithinDays) {
                if (this.dueWithinDays.hasOwnProperty(key))
                    (data["dueWithinDays"] as any)[key] = (this.dueWithinDays as any)[key];
            }
        }
        data["noExpiry"] = this.noExpiry;
        data["totalActionable"] = this.totalActionable;
        return data;
    }
}

export interface IInventoryDigestCountsResponse {
    expired?: number;
    dueWithinDays?: { [key: string]: number; } | undefined;
    noExpiry?: number;
    totalActionable?: number;
}

/** Inventory agent digest with grouped expiry sections and deterministic hints. */
export class InventoryDigestResponse implements IInventoryDigestResponse {
    asOf?: Date;
    windowsDays?: number[] | undefined;
    counts?: InventoryDigestCountsResponse;
    expired?: InventoryAgentItemResponse[] | undefined;
    dueWithinDays?: { [key: string]: InventoryAgentItemResponse[]; } | undefined;
    noExpiry?: InventoryAgentItemResponse[] | undefined;
    hints?: InventoryAgentHintResponse[] | undefined;

    constructor(data?: IInventoryDigestResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.asOf = _data["asOf"] ? new Date(_data["asOf"].toString()) : undefined as any;
            if (Array.isArray(_data["windowsDays"])) {
                this.windowsDays = [] as any;
                for (let item of _data["windowsDays"])
                    this.windowsDays!.push(item);
            }
            this.counts = _data["counts"] ? InventoryDigestCountsResponse.fromJS(_data["counts"]) : undefined as any;
            if (Array.isArray(_data["expired"])) {
                this.expired = [] as any;
                for (let item of _data["expired"])
                    this.expired!.push(InventoryAgentItemResponse.fromJS(item));
            }
            if (_data["dueWithinDays"]) {
                this.dueWithinDays = {} as any;
                for (let key in _data["dueWithinDays"]) {
                    if (_data["dueWithinDays"].hasOwnProperty(key))
                        (this.dueWithinDays as any)![key] = _data["dueWithinDays"][key] ? _data["dueWithinDays"][key].map((i: any) => InventoryAgentItemResponse.fromJS(i)) : [];
                }
            }
            if (Array.isArray(_data["noExpiry"])) {
                this.noExpiry = [] as any;
                for (let item of _data["noExpiry"])
                    this.noExpiry!.push(InventoryAgentItemResponse.fromJS(item));
            }
            if (Array.isArray(_data["hints"])) {
                this.hints = [] as any;
                for (let item of _data["hints"])
                    this.hints!.push(InventoryAgentHintResponse.fromJS(item));
            }
        }
    }

    static fromJS(data: any): InventoryDigestResponse {
        data = typeof data === 'object' ? data : {};
        let result = new InventoryDigestResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["asOf"] = this.asOf ? this.asOf.toISOString() : undefined as any;
        if (Array.isArray(this.windowsDays)) {
            data["windowsDays"] = [];
            for (let item of this.windowsDays)
                data["windowsDays"].push(item);
        }
        data["counts"] = this.counts ? this.counts.toJSON() : undefined as any;
        if (Array.isArray(this.expired)) {
            data["expired"] = [];
            for (let item of this.expired)
                data["expired"].push(item ? item.toJSON() : undefined as any);
        }
        if (this.dueWithinDays) {
            data["dueWithinDays"] = {};
            for (let key in this.dueWithinDays) {
                if (this.dueWithinDays.hasOwnProperty(key))
                    (data["dueWithinDays"] as any)[key] = (this.dueWithinDays as any)[key];
            }
        }
        if (Array.isArray(this.noExpiry)) {
            data["noExpiry"] = [];
            for (let item of this.noExpiry)
                data["noExpiry"].push(item ? item.toJSON() : undefined as any);
        }
        if (Array.isArray(this.hints)) {
            data["hints"] = [];
            for (let item of this.hints)
                data["hints"].push(item ? item.toJSON() : undefined as any);
        }
        return data;
    }
}

/** Inventory agent digest with grouped expiry sections and deterministic hints. */
export interface IInventoryDigestResponse {
    asOf?: Date;
    windowsDays?: number[] | undefined;
    counts?: InventoryDigestCountsResponse;
    expired?: InventoryAgentItemResponse[] | undefined;
    dueWithinDays?: { [key: string]: InventoryAgentItemResponse[]; } | undefined;
    noExpiry?: InventoryAgentItemResponse[] | undefined;
    hints?: InventoryAgentHintResponse[] | undefined;
}

export class InventoryItemRequest implements IInventoryItemRequest {
    name!: string;
    quantity?: number;
    unit?: Unit;
    expiryDate?: Date | undefined;
    category?: string | undefined;
    location?: string | undefined;
    purchasedDate?: Date | undefined;
    openedDate?: Date | undefined;
    notes?: string | undefined;

    constructor(data?: IInventoryItemRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.name = _data["name"];
            this.quantity = _data["quantity"];
            this.unit = _data["unit"];
            this.expiryDate = _data["expiryDate"] ? new Date(_data["expiryDate"].toString()) : undefined as any;
            this.category = _data["category"];
            this.location = _data["location"];
            this.purchasedDate = _data["purchasedDate"] ? new Date(_data["purchasedDate"].toString()) : undefined as any;
            this.openedDate = _data["openedDate"] ? new Date(_data["openedDate"].toString()) : undefined as any;
            this.notes = _data["notes"];
        }
    }

    static fromJS(data: any): InventoryItemRequest {
        data = typeof data === 'object' ? data : {};
        let result = new InventoryItemRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["name"] = this.name;
        data["quantity"] = this.quantity;
        data["unit"] = this.unit;
        data["expiryDate"] = this.expiryDate ? this.expiryDate.toISOString() : undefined as any;
        data["category"] = this.category;
        data["location"] = this.location;
        data["purchasedDate"] = this.purchasedDate ? this.purchasedDate.toISOString() : undefined as any;
        data["openedDate"] = this.openedDate ? this.openedDate.toISOString() : undefined as any;
        data["notes"] = this.notes;
        return data;
    }
}

export interface IInventoryItemRequest {
    name: string;
    quantity?: number;
    unit?: Unit;
    expiryDate?: Date | undefined;
    category?: string | undefined;
    location?: string | undefined;
    purchasedDate?: Date | undefined;
    openedDate?: Date | undefined;
    notes?: string | undefined;
}

export class InventoryItemResponse implements IInventoryItemResponse {
    id!: string | undefined;
    name!: string | undefined;
    quantity?: number;
    unit?: Unit;
    expiryDate?: Date | undefined;
    category?: string | undefined;
    location?: string | undefined;
    purchasedDate?: Date | undefined;
    openedDate?: Date | undefined;
    notes?: string | undefined;

    constructor(data?: IInventoryItemResponse) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.id = _data["id"];
            this.name = _data["name"];
            this.quantity = _data["quantity"];
            this.unit = _data["unit"];
            this.expiryDate = _data["expiryDate"] ? new Date(_data["expiryDate"].toString()) : undefined as any;
            this.category = _data["category"];
            this.location = _data["location"];
            this.purchasedDate = _data["purchasedDate"] ? new Date(_data["purchasedDate"].toString()) : undefined as any;
            this.openedDate = _data["openedDate"] ? new Date(_data["openedDate"].toString()) : undefined as any;
            this.notes = _data["notes"];
        }
    }

    static fromJS(data: any): InventoryItemResponse {
        data = typeof data === 'object' ? data : {};
        let result = new InventoryItemResponse();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["id"] = this.id;
        data["name"] = this.name;
        data["quantity"] = this.quantity;
        data["unit"] = this.unit;
        data["expiryDate"] = this.expiryDate ? this.expiryDate.toISOString() : undefined as any;
        data["category"] = this.category;
        data["location"] = this.location;
        data["purchasedDate"] = this.purchasedDate ? this.purchasedDate.toISOString() : undefined as any;
        data["openedDate"] = this.openedDate ? this.openedDate.toISOString() : undefined as any;
        data["notes"] = this.notes;
        return data;
    }
}

export interface IInventoryItemResponse {
    id: string | undefined;
    name: string | undefined;
    quantity?: number;
    unit?: Unit;
    expiryDate?: Date | undefined;
    category?: string | undefined;
    location?: string | undefined;
    purchasedDate?: Date | undefined;
    openedDate?: Date | undefined;
    notes?: string | undefined;
}

export enum InventoryItemUrgency {
    Expired = "Expired",
    DueToday = "DueToday",
    DueSoon = "DueSoon",
    Later = "Later",
    NoExpiry = "NoExpiry",
}

export class LoginRequest implements ILoginRequest {
    username?: string | undefined;
    password?: string | undefined;

    constructor(data?: ILoginRequest) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            this.username = _data["username"];
            this.password = _data["password"];
        }
    }

    static fromJS(data: any): LoginRequest {
        data = typeof data === 'object' ? data : {};
        let result = new LoginRequest();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        data["username"] = this.username;
        data["password"] = this.password;
        return data;
    }
}

export interface ILoginRequest {
    username?: string | undefined;
    password?: string | undefined;
}

export class ProblemDetails implements IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;

    constructor(data?: IProblemDetails) {
        if (data) {
            for (var property in data) {
                if (data.hasOwnProperty(property))
                    (this as any)[property] = (data as any)[property];
            }
        }
    }

    init(_data?: any) {
        if (_data) {
            for (var property in _data) {
                if (_data.hasOwnProperty(property))
                    this[property] = _data[property];
            }
            this.type = _data["type"];
            this.title = _data["title"];
            this.status = _data["status"];
            this.detail = _data["detail"];
            this.instance = _data["instance"];
        }
    }

    static fromJS(data: any): ProblemDetails {
        data = typeof data === 'object' ? data : {};
        let result = new ProblemDetails();
        result.init(data);
        return result;
    }

    toJSON(data?: any) {
        data = typeof data === 'object' ? data : {};
        for (var property in this) {
            if (this.hasOwnProperty(property))
                data[property] = this[property];
        }
        data["type"] = this.type;
        data["title"] = this.title;
        data["status"] = this.status;
        data["detail"] = this.detail;
        data["instance"] = this.instance;
        return data;
    }
}

export interface IProblemDetails {
    type?: string | undefined;
    title?: string | undefined;
    status?: number | undefined;
    detail?: string | undefined;
    instance?: string | undefined;

    [key: string]: any;
}

export enum Unit {
    None = "None",
    Part = "Part",
    Gram = "Gram",
    Litre = "Litre",
    Milliliter = "Milliliter",
    Cup = "Cup",
    Tablespoon = "Tablespoon",
    Teaspoon = "Teaspoon",
    Ounce = "Ounce",
    Pound = "Pound",
    Kilogram = "Kilogram",
    Gallon = "Gallon",
    Quart = "Quart",
    Pint = "Pint",
    FluidOunce = "FluidOunce",
    CubicCentimeter = "CubicCentimeter",
    CubicMeter = "CubicMeter",
    CubicInch = "CubicInch",
}

export class SwaggerException extends Error {
    override message: string;
    status: number;
    response: string;
    headers: { [key: string]: any; };
    result: any;

    constructor(message: string, status: number, response: string, headers: { [key: string]: any; }, result: any) {
        super();

        this.message = message;
        this.status = status;
        this.response = response;
        this.headers = headers;
        this.result = result;
    }

    protected isSwaggerException = true;

    static isSwaggerException(obj: any): obj is SwaggerException {
        return obj.isSwaggerException === true;
    }
}

function throwException(message: string, status: number, response: string, headers: { [key: string]: any; }, result?: any): any {
    throw new SwaggerException(message, status, response, headers, result);
}

function isAxiosError(obj: any): obj is AxiosError {
    return obj && obj.isAxiosError === true;
}