using FluentAssertions;
using Stockpile.Api.Contracts.Mappers;
using Stockpile.Api.Contracts.Requests;
using Stockpile.Domain.Entities;
using Stockpile.Domain.Enums;

namespace Stockpile.UnitTests.Mappers;

[Collection("Mapper Tests")]
public class InventoryItemMapperTests
{
    [Fact]
    public void MapTo_WithIdUserIdUsername_MapsCorrectly()
    {
        var request = new InventoryItemRequest
        {
            Name = "Milk",
            Quantity = 2,
            Unit = Unit.Litre,
            ExpiryDate = DateTime.Today.AddDays(5)
        };
        var entity = request.MapTo("item123", "user456", "DemoUser");
        entity.Id.Should().Be("item123");
        entity.UserId.Should().Be("user456");
        entity.Username.Should().Be("DemoUser");
        entity.Name.Should().Be(request.Name);
        entity.Quantity.Should().Be(request.Quantity);
        entity.Unit.Should().Be(request.Unit);
        entity.ExpiryDate.Should().Be(request.ExpiryDate);
    }

    [Fact]
    public void MapTo_WithUserIdUsername_MapsCorrectly()
    {
        var request = new InventoryItemRequest
        {
            Name = "Eggs",
            Quantity = 12,
            Unit = Unit.Part,
            ExpiryDate = null
        };
        var entity = request.MapTo("user789", "DemoUser2");
        entity.Id.Should().NotBeNullOrEmpty(); // Expect Id to be generated by InventoryItem constructor
        entity.UserId.Should().Be("user789");
        entity.Username.Should().Be("DemoUser2");
        entity.Name.Should().Be(request.Name);
        entity.Quantity.Should().Be(request.Quantity);
        entity.Unit.Should().Be(request.Unit);
        entity.ExpiryDate.Should().BeNull();
    }

    [Fact]
    public void MapFrom_MapsCorrectly()
    {
        var entity = new InventoryItem
        {
            Id = "item999",
            Name = "Bread",
            Quantity = 1,
            Unit = Unit.Part,
            ExpiryDate = DateTime.Today.AddDays(2),
            UserId = string.Empty,
            Username = string.Empty
        };
        var response = entity.MapFrom();
        response.Id.Should().Be(entity.Id);
        response.Name.Should().Be(entity.Name);
        response.Quantity.Should().Be(entity.Quantity);
        response.Unit.Should().Be(entity.Unit);
        response.ExpiryDate.Should().Be(entity.ExpiryDate);
    }
}
