//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.5.0.0 (NJsonSchema v11.4.0.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* eslint-disable */
// ReSharper disable InconsistentNaming

import axios, { AxiosError } from "axios";
import type {
  AxiosInstance,
  AxiosRequestConfig,
  AxiosResponse,
  CancelToken,
} from "axios";

export interface IApiClient {
  /**
   * @param body (optional)
   * @return OK
   */
  login(body?: LoginRequest | undefined, signal?: AbortSignal): Promise<void>;
  /**
   * @return OK
   */
  stockAll(signal?: AbortSignal): Promise<InventoryItemResponse[]>;
  /**
   * @param body (optional)
   * @return Created
   */
  stockPOST(
    body?: InventoryItemRequest | undefined,
    signal?: AbortSignal,
  ): Promise<InventoryItemResponse>;
  /**
   * @return OK
   */
  stockAll2(id: string, signal?: AbortSignal): Promise<InventoryItemResponse[]>;
  /**
   * @param body (optional)
   * @return OK
   */
  stockPUT(
    id: string,
    body?: InventoryItemRequest | undefined,
    signal?: AbortSignal,
  ): Promise<InventoryItemResponse>;
  /**
   * @return No Content
   */
  stockDELETE(id: string, signal?: AbortSignal): Promise<void>;
}

export class ApiClient implements IApiClient {
  protected instance: AxiosInstance;
  protected baseUrl: string;
  protected jsonParseReviver: ((key: string, value: any) => any) | undefined =
    undefined;

  constructor(baseUrl?: string, instance?: AxiosInstance) {
    this.instance = instance || axios.create();

    this.baseUrl = baseUrl ?? "";
  }

  /**
   * @param body (optional)
   * @return OK
   */
  login(body?: LoginRequest | undefined, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + "/api/Auth/login";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
      },
      signal,
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_);
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(
          url_,
          _response,
          (_response: AxiosResponse) => this.processLogin(_response),
        );
      });
  }

  protected processLogin(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }

  /**
   * @return OK
   */
  stockAll(signal?: AbortSignal): Promise<InventoryItemResponse[]> {
    let url_ = this.baseUrl + "/api/Stock";
    url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json",
      },
      signal,
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_);
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(
          url_,
          _response,
          (_response: AxiosResponse) => this.processStockAll(_response),
        );
      });
  }

  protected processStockAll(
    response: AxiosResponse,
  ): Promise<InventoryItemResponse[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      if (Array.isArray(resultData200)) {
        result200 = [] as any;
        for (let item of resultData200)
          result200!.push(InventoryItemResponse.fromJS(item));
      } else {
        result200 = null as any;
      }
      return Promise.resolve<InventoryItemResponse[]>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<InventoryItemResponse[]>(null as any);
  }

  /**
   * @param body (optional)
   * @return Created
   */
  stockPOST(
    body?: InventoryItemRequest | undefined,
    signal?: AbortSignal,
  ): Promise<InventoryItemResponse> {
    let url_ = this.baseUrl + "/api/Stock";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "POST",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      signal,
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_);
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(
          url_,
          _response,
          (_response: AxiosResponse) => this.processStockPOST(_response),
        );
      });
  }

  protected processStockPOST(
    response: AxiosResponse,
  ): Promise<InventoryItemResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 201) {
      const _responseText = response.data;
      let result201: any = null;
      let resultData201 = _responseText;
      result201 = InventoryItemResponse.fromJS(resultData201);
      return Promise.resolve<InventoryItemResponse>(result201);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<InventoryItemResponse>(null as any);
  }

  /**
   * @return OK
   */
  stockAll2(
    id: string,
    signal?: AbortSignal,
  ): Promise<InventoryItemResponse[]> {
    let url_ = this.baseUrl + "/api/Stock/{id}";
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
      method: "GET",
      url: url_,
      headers: {
        Accept: "application/json",
      },
      signal,
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_);
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(
          url_,
          _response,
          (_response: AxiosResponse) => this.processStockAll2(_response),
        );
      });
  }

  protected processStockAll2(
    response: AxiosResponse,
  ): Promise<InventoryItemResponse[]> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      if (Array.isArray(resultData200)) {
        result200 = [] as any;
        for (let item of resultData200)
          result200!.push(InventoryItemResponse.fromJS(item));
      } else {
        result200 = null as any;
      }
      return Promise.resolve<InventoryItemResponse[]>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<InventoryItemResponse[]>(null as any);
  }

  /**
   * @param body (optional)
   * @return OK
   */
  stockPUT(
    id: string,
    body?: InventoryItemRequest | undefined,
    signal?: AbortSignal,
  ): Promise<InventoryItemResponse> {
    let url_ = this.baseUrl + "/api/Stock/{id}";
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(body);

    let options_: AxiosRequestConfig = {
      data: content_,
      method: "PUT",
      url: url_,
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      signal,
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_);
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(
          url_,
          _response,
          (_response: AxiosResponse) => this.processStockPUT(_response),
        );
      });
  }

  protected processStockPUT(
    response: AxiosResponse,
  ): Promise<InventoryItemResponse> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 200) {
      const _responseText = response.data;
      let result200: any = null;
      let resultData200 = _responseText;
      result200 = InventoryItemResponse.fromJS(resultData200);
      return Promise.resolve<InventoryItemResponse>(result200);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<InventoryItemResponse>(null as any);
  }

  /**
   * @return No Content
   */
  stockDELETE(id: string, signal?: AbortSignal): Promise<void> {
    let url_ = this.baseUrl + "/api/Stock/{id}";
    if (id === undefined || id === null)
      throw new globalThis.Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    url_ = url_.replace(/[?&]$/, "");

    let options_: AxiosRequestConfig = {
      method: "DELETE",
      url: url_,
      headers: {},
      signal,
    };

    return this.transformOptions(options_)
      .then((transformedOptions_) => {
        return this.instance.request(transformedOptions_);
      })
      .catch((_error: any) => {
        if (isAxiosError(_error) && _error.response) {
          return _error.response;
        } else {
          throw _error;
        }
      })
      .then((_response: AxiosResponse) => {
        return this.transformResult(
          url_,
          _response,
          (_response: AxiosResponse) => this.processStockDELETE(_response),
        );
      });
  }

  protected processStockDELETE(response: AxiosResponse): Promise<void> {
    const status = response.status;
    let _headers: any = {};
    if (response.headers && typeof response.headers === "object") {
      for (const k in response.headers) {
        if (response.headers.hasOwnProperty(k)) {
          _headers[k] = response.headers[k];
        }
      }
    }
    if (status === 204) {
      const _responseText = response.data;
      return Promise.resolve<void>(null as any);
    } else if (status !== 200 && status !== 204) {
      const _responseText = response.data;
      return throwException(
        "An unexpected server error occurred.",
        status,
        _responseText,
        _headers,
      );
    }
    return Promise.resolve<void>(null as any);
  }
}

export class InventoryItemRequest implements IInventoryItemRequest {
  name!: string | undefined;
  quantity?: number;
  unit?: Unit;
  expiryDate?: Date | undefined;

  constructor(data?: IInventoryItemRequest) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.name = _data["name"];
      this.quantity = _data["quantity"];
      this.unit = _data["unit"];
      this.expiryDate = _data["expiryDate"]
        ? new Date(_data["expiryDate"].toString())
        : (undefined as any);
    }
  }

  static fromJS(data: any): InventoryItemRequest {
    data = typeof data === "object" ? data : {};
    let result = new InventoryItemRequest();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["name"] = this.name;
    data["quantity"] = this.quantity;
    data["unit"] = this.unit;
    data["expiryDate"] = this.expiryDate
      ? this.expiryDate.toISOString()
      : (undefined as any);
    return data;
  }
}

export interface IInventoryItemRequest {
  name: string | undefined;
  quantity?: number;
  unit?: Unit;
  expiryDate?: Date | undefined;
}

export class InventoryItemResponse implements IInventoryItemResponse {
  id!: string | undefined;
  name!: string | undefined;
  quantity?: number;
  unit?: Unit;
  expiryDate?: Date | undefined;

  constructor(data?: IInventoryItemResponse) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.id = _data["id"];
      this.name = _data["name"];
      this.quantity = _data["quantity"];
      this.unit = _data["unit"];
      this.expiryDate = _data["expiryDate"]
        ? new Date(_data["expiryDate"].toString())
        : (undefined as any);
    }
  }

  static fromJS(data: any): InventoryItemResponse {
    data = typeof data === "object" ? data : {};
    let result = new InventoryItemResponse();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["name"] = this.name;
    data["quantity"] = this.quantity;
    data["unit"] = this.unit;
    data["expiryDate"] = this.expiryDate
      ? this.expiryDate.toISOString()
      : (undefined as any);
    return data;
  }
}

export interface IInventoryItemResponse {
  id: string | undefined;
  name: string | undefined;
  quantity?: number;
  unit?: Unit;
  expiryDate?: Date | undefined;
}

export class LoginRequest implements ILoginRequest {
  username?: string | undefined;
  password?: string | undefined;

  constructor(data?: ILoginRequest) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (this as any)[property] = (data as any)[property];
      }
    }
  }

  init(_data?: any) {
    if (_data) {
      this.username = _data["username"];
      this.password = _data["password"];
    }
  }

  static fromJS(data: any): LoginRequest {
    data = typeof data === "object" ? data : {};
    let result = new LoginRequest();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["username"] = this.username;
    data["password"] = this.password;
    return data;
  }
}

export interface ILoginRequest {
  username?: string | undefined;
  password?: string | undefined;
}

export enum Unit {
  _1 = 1,
  _2 = 2,
  _3 = 3,
  _4 = 4,
  _5 = 5,
  _6 = 6,
  _7 = 7,
  _8 = 8,
  _9 = 9,
  _10 = 10,
  _11 = 11,
  _12 = 12,
  _13 = 13,
  _14 = 14,
  _15 = 15,
  _16 = 16,
  _17 = 17,
}

export class SwaggerException extends Error {
  override message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any,
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isSwaggerException = true;

  static isSwaggerException(obj: any): obj is SwaggerException {
    return obj.isSwaggerException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any,
): any {
  throw new SwaggerException(message, status, response, headers, result);
}

function isAxiosError(obj: any): obj is AxiosError {
  return obj && obj.isAxiosError === true;
}
